<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>977effef-fb76-42c4-bcbe-9415b9502ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div/div/div[2]/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .thumb-wrapper > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>617f5cf7-4646-482e-aed5-11883e964869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./compendium/aerospace_centre.jpg</value>
      <webElementGuid>336079dc-9510-45e2-9778-16d1a4618ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>167px</value>
      <webElementGuid>73336bd7-2326-49fd-bc68-0f6c6394ec29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>265px</value>
      <webElementGuid>bfa178c6-5fb1-439b-a744-b40b454fddff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@id=&quot;wrapper&quot;]/div[@id=&quot;wrapper&quot;]/div[@class=&quot;container middleContent&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;gallery&quot;]/div[@class=&quot;container middleContent&quot;]/div[@class=&quot;thumb-album shadow&quot;]/div[@class=&quot;thumb-wrapper&quot;]/a[1]/img[1]</value>
      <webElementGuid>b72dff02-1389-48f2-ac8b-991c917a9582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div/div[2]/div[2]/div/a/img</value>
      <webElementGuid>2648d990-cf07-4ccf-9aea-a95507bc213f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>acf810e1-226a-46ff-a7a5-856f1cb964d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './compendium/aerospace_centre.jpg']</value>
      <webElementGuid>6fc8fd8d-81f3-409b-b0c5-2713527dc180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
