<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b0269354-6f8b-4bc7-93d4-7e79fdb9bb99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/a/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Image Image Monitors From ₹9999&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65731c08-38fd-4142-ace5-43da12dc6e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-assets-web.flixcart.com/www/linchpin/batman-returns/images/fk-default-image-75ff340b.png?q=90</value>
      <webElementGuid>8a2803b6-c4b9-4c73-bff2-203bc3d06e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>052b43be-bda0-4405-a16f-19d4712c4666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image</value>
      <webElementGuid>c09af3e7-8310-4f38-aa9b-eaf4a1189317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;q8WwEU&quot;]/div[@class=&quot;_3zsGrb&quot;]/div[@class=&quot;_2-LWwB&quot;]/div[1]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;css-175oi2r r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;css-175oi2r r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;_1ui5b4&quot;]/div[@class=&quot;yAlKeh&quot;]/div[@class=&quot;_2L0uxW&quot;]/div[@class=&quot;_3116_u&quot;]/div[@class=&quot;_1yQHx8 _2UnIQ_ _3ak8Rd _1kAmyc&quot;]/div[1]/div[@class=&quot;css-175oi2r r-13awgt0 r-eqz5dr&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;_3n8fnawg _3n8fnaod _3n8fnag9 _3n8fna1 _3n8fna85 _1i2djtb9 _1i2djt0&quot;]/div[1]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;_3MlEpv&quot;]/div[@class=&quot;tLbyDf&quot;]/div[@class=&quot;_25HC_u&quot;]/div[@class=&quot;css-175oi2r&quot;]/div[1]/div[1]/a[@class=&quot;_3n8fnawg _3n8fnata _3n8fnal6 _3n8fna4y _3n8fnad2 _1i2djtb9 _1i2djtk9 _1i2djti0 _1i2djt9f _1i2djt76 _1i2djtdi _1i2djtfr _1i2djt2o _1i2djt4x&quot;]/div[@class=&quot;_3n8fnawg _3n8fnaod _3n8fnag9 _3n8fna1 _3n8fna85 _1i2djtb9 _1i2djt0 _1i2djt90 _1i2djt91 _1i2djt92 _1i2djt6r _1i2djt6s _1i2djt6t _1i2djt29 _1i2djt2a _1i2djt2b _1i2djt4i _1i2djt4j _1i2djt4k&quot;]/div[@class=&quot;_3n8fnawg _3n8fnaod _3n8fnag9 _3n8fna1 _3n8fna85 _1i2djtb9 _1i2djt0 _1i2djt90 _1i2djt6r _1i2djt29 _1i2djt4i&quot;]/div[@class=&quot;zlQd20 _1eDlvI&quot;]/img[1]</value>
      <webElementGuid>7abcb8e7-1908-4e51-adf7-4e49d72fb3ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/a/div/div/div/img</value>
      <webElementGuid>cf419f77-1496-485b-bf87-39c241bee3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Image'])[24]</value>
      <webElementGuid>c34c7f5f-87fd-4062-8986-a3a610fbdec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div/div/div/img</value>
      <webElementGuid>b23584c4-aff7-48db-8634-930e18c800de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static-assets-web.flixcart.com/www/linchpin/batman-returns/images/fk-default-image-75ff340b.png?q=90' and @alt = 'Image']</value>
      <webElementGuid>71b8b848-5193-4ef2-976c-11275907adc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
